import { Injectable, Logger, ServiceUnavailableException } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import { MercadoPagoApiError } from './mercadopago-api.error';

export interface MercadoPagoAutoRecurring {
  frequency: number;
  frequency_type: string;
  transaction_amount: number;
  currency_id: string;
}

export interface CreateMercadoPagoSubscriptionInput {
  reason: string;
  payerEmail: string;
  externalReference: string;
  autoRecurring: MercadoPagoAutoRecurring;
  backUrl: string;
  cardTokenId: string;
}

export interface MercadoPagoSubscriptionCreated {
  id: string;
  init_point: string;
  status: string;
  /** Fecha del próximo cobro, si MercadoPago la devuelve. Usado por
   * `parsePeriodEnd()` en el flujo síncrono de checkout con tarjeta. */
  next_payment_date?: string;
}

/**
 * `GET /authorized_payments/{id}` — "An invoice generated by a subscription
 * billing cycle" (schema `AuthorizedPayment` del OpenAPI oficial, ver
 * `specs/mercadopago-activar-plan-en-cobro-real/design.md` §0.1-§0.2).
 * Estado AUTORITATIVO del cobro real de un ciclo de facturación — distinto
 * del cargo de validación mínima de tarjeta que ocurre al crear la
 * `preapproval` (`POST /preapproval`).
 *
 * `preapproval_id` es el campo de correlación con la `Subscription` local
 * (`mp_preapproval_id`) — NUNCA usar el `id` de este recurso (que es el id
 * del pago/factura, no de la suscripción) para esa búsqueda.
 */
export interface MercadoPagoAuthorizedPayment {
  id: string;
  preapproval_id: string;
  status: 'scheduled' | 'processed' | 'recycling' | 'cancelled';
  /** String libre (sin enum cerrado) — solo informativo, ver design.md §0.2. */
  status_detail?: string;
  transaction_amount?: number;
  payment?: { id: number; status?: string; status_detail?: string };
}

/**
 * Cliente HTTP para la API de MercadoPago (pagos recurrentes, planes
 * pro/family). Reemplaza `flow-client.service.ts`. Sin dependencias de
 * cliente HTTP: usa el `fetch` global de Node 20+ (mismo patrón que
 * `FlowClientService`/`RecaptchaService`).
 *
 * Autenticación: header `Authorization: Bearer <MERCADOPAGO_ACCESS_TOKEN>`
 * en toda llamada — SIN firma HMAC de request (a diferencia de Flow).
 *
 * Sin sandbox separado: única URL `https://api.mercadopago.com` para test y
 * producción; se distinguen solo por el tipo de credencial (verificado
 * contra `spec3.json` oficial y snapshots de `web.archive.org`, ver
 * `specs/migrar-pagos-a-mercadopago/design.md` §1).
 *
 * Degrada con warning si falta la credencial: la app arranca igual, cada
 * endpoint de pago responde 503 solo cuando se invoca (`assertConfigured()`),
 * sin bloquear el bootstrap completo.
 */
@Injectable()
export class MercadoPagoClientService {
  private readonly logger = new Logger(MercadoPagoClientService.name);
  private readonly baseUrl = 'https://api.mercadopago.com';
  private readonly accessToken: string | undefined;

  constructor(private readonly config: ConfigService) {
    this.accessToken = this.config.get<string>('MERCADOPAGO_ACCESS_TOKEN') || undefined;

    if (!this.accessToken) {
      this.logger.warn(
        'MERCADOPAGO_ACCESS_TOKEN ausente: pagos con MercadoPago deshabilitados en este entorno.',
      ); // NO lanza — mismo patrón de degradación elegante que Flow/Resend.
    }
  }

  /** true si hay credencial de MercadoPago configurada. */
  isConfigured(): boolean {
    return !!this.accessToken;
  }

  /** Lanza 503 sin red si falta la credencial. */
  assertConfigured(): void {
    if (!this.isConfigured()) {
      throw new ServiceUnavailableException(
        'Pagos con MercadoPago no están disponibles en este entorno (credenciales no configuradas).',
      );
    }
  }

  // ── Transporte HTTP ──────────────────────────────────────────────────────
  private async request<T = Record<string, any>>(
    path: string,
    init: RequestInit,
  ): Promise<T> {
    this.assertConfigured();
    const url = `${this.baseUrl}${path}`;
    let res: Response;
    try {
      res = await fetch(url, {
        ...init,
        headers: {
          Authorization: `Bearer ${this.accessToken}`,
          'Content-Type': 'application/json',
          ...(init.headers ?? {}),
        },
        signal: AbortSignal.timeout(10000),
      });
    } catch (err) {
      // Error de red / DNS / timeout (AbortError): 503, no crashea.
      this.logger.error(
        `Error de red llamando a MercadoPago (${url}): ${err instanceof Error ? err.message : String(err)}`,
      );
      throw new ServiceUnavailableException(
        'MercadoPago no está disponible en este momento. Intenta nuevamente.',
      );
    }

    if (!res.ok) {
      let detail = '';
      try {
        detail = await res.text();
      } catch {
        // ignorar: el detalle es solo para el log
      }
      this.logger.error(`MercadoPago respondió ${res.status} en ${url}: ${detail}`);
      // Body JSON parseable a objeto → error tipado inspeccionable por
      // PaymentsService. NUNCA debe llegar crudo al cliente HTTP.
      let parsed: unknown;
      try {
        parsed = JSON.parse(detail);
      } catch {
        parsed = undefined;
      }
      if (parsed !== null && typeof parsed === 'object') {
        throw new MercadoPagoApiError(res.status, parsed as Record<string, any>);
      }
      // Body no parseable: 503 genérica.
      throw new ServiceUnavailableException(
        'MercadoPago no está disponible en este momento. Intenta nuevamente.',
      );
    }

    try {
      return (await res.json()) as T;
    } catch (err) {
      this.logger.error(
        `Respuesta de MercadoPago no es JSON válido (${url}): ${err instanceof Error ? err.message : String(err)}`,
      );
      throw new ServiceUnavailableException(
        'MercadoPago no está disponible en este momento. Intenta nuevamente.',
      );
    }
  }

  // ── Recursos de la API de MercadoPago ───────────────────────────────────

  /**
   * POST /preapproval — crea la suscripción "sin plan asociado" (SIN
   * `preapproval_plan_id`) CON `card_token_id` + `status: 'authorized'`
   * explícito (ver `specs/mercadopago-checkout-bricks-tarjeta/design.md`
   * §0, Fuente C): confirmado contra el schema OpenAPI oficial en vivo,
   * acotando el bloque `requestBody`, que `POST /preapproval` NO exige
   * `issuer_id`/`payment_method_id`/`payment_method_option_id`/
   * `installments` (a diferencia de `POST /v1/payments`) — solo
   * `card_token_id` sumado a los campos ya usados por el flujo anterior.
   * El `card_token_id` lo genera el Brick `<CardPayment>` del lado del
   * frontend; nunca es el número de tarjeta/CVV crudo.
   */
  async createSubscription(
    input: CreateMercadoPagoSubscriptionInput,
  ): Promise<MercadoPagoSubscriptionCreated> {
    const res = await this.request<Record<string, any>>('/preapproval', {
      method: 'POST',
      body: JSON.stringify({
        reason: input.reason,
        payer_email: input.payerEmail,
        external_reference: input.externalReference,
        auto_recurring: input.autoRecurring,
        back_url: input.backUrl,
        card_token_id: input.cardTokenId,
        status: 'authorized',
      }),
    });
    const id = res.id;
    const initPoint = res.init_point;
    if (!id || !initPoint) {
      this.logger.error(
        `POST /preapproval no devolvió id/init_point reconocibles. Respuesta: ${JSON.stringify(res)}`,
      );
      throw new ServiceUnavailableException('MercadoPago no confirmó la creación de la suscripción.');
    }
    return {
      id: String(id),
      init_point: String(initPoint),
      status: String(res.status ?? 'pending'),
      next_payment_date: typeof res.next_payment_date === 'string' ? res.next_payment_date : undefined,
    };
  }

  /** GET /preapproval/{id} — estado autoritativo de la suscripción (nunca confiar solo en el webhook). */
  async getSubscription(id: string): Promise<Record<string, any>> {
    return this.request<Record<string, any>>(`/preapproval/${encodeURIComponent(id)}`, {
      method: 'GET',
    });
  }

  /**
   * PUT /preapproval/{id} con `{"status": "cancelled"}` — endpoint
   * verificado contra la especificación OpenAPI oficial de MercadoPago
   * (`updateSubscription`, ver design.md §1).
   */
  async cancelSubscription(id: string): Promise<void> {
    await this.request<Record<string, any>>(`/preapproval/${encodeURIComponent(id)}`, {
      method: 'PUT',
      body: JSON.stringify({ status: 'cancelled' }),
    });
  }

  /**
   * GET /authorized_payments/{id} — estado autoritativo del cobro real de un
   * ciclo de facturación. `PaymentsService` SIEMPRE llama esto antes de
   * decidir activar/rechazar una `Subscription` tras un webhook
   * `subscription_authorized_payment` — nunca confía en el payload crudo del
   * webhook (R5, R6).
   */
  async getAuthorizedPayment(id: string): Promise<MercadoPagoAuthorizedPayment> {
    const res = await this.request<Record<string, any>>(
      `/authorized_payments/${encodeURIComponent(id)}`,
      { method: 'GET' },
    );
    return this.parseAuthorizedPayment(res);
  }

  /**
   * GET /authorized_payments?preapproval_id=&status=&limit= — búsqueda de
   * invoices por suscripción, usada por la reconciliación de respaldo
   * (`PaymentsService.reconcilePendingPayments()`, R15-R16). Endpoint
   * confirmado contra el spec OpenAPI oficial (design.md §0.4).
   */
  async searchAuthorizedPayments(input: {
    preapprovalId: string;
    status?: string;
    limit?: number;
  }): Promise<{ results: MercadoPagoAuthorizedPayment[] }> {
    const params = new URLSearchParams();
    params.set('preapproval_id', input.preapprovalId);
    if (input.status) params.set('status', input.status);
    params.set('limit', String(input.limit ?? 10));

    const res = await this.request<Record<string, any>>(
      `/authorized_payments?${params.toString()}`,
      { method: 'GET' },
    );
    const raw: Record<string, any>[] = Array.isArray(res?.results)
      ? res.results
      : Array.isArray(res)
        ? (res as unknown as Record<string, any>[])
        : [];
    return { results: raw.map((item) => this.parseAuthorizedPayment(item)) };
  }

  /** Normaliza la respuesta cruda de `authorized_payments` al tipo tipado local. */
  private parseAuthorizedPayment(raw: Record<string, any>): MercadoPagoAuthorizedPayment {
    return {
      id: String(raw?.id ?? ''),
      preapproval_id: String(raw?.preapproval_id ?? ''),
      status: raw?.status as MercadoPagoAuthorizedPayment['status'],
      status_detail: typeof raw?.status_detail === 'string' ? raw.status_detail : undefined,
      transaction_amount:
        typeof raw?.transaction_amount === 'number' ? raw.transaction_amount : undefined,
      payment:
        raw?.payment && typeof raw.payment === 'object'
          ? {
              id: Number(raw.payment.id),
              status: typeof raw.payment.status === 'string' ? raw.payment.status : undefined,
              status_detail:
                typeof raw.payment.status_detail === 'string' ? raw.payment.status_detail : undefined,
            }
          : undefined,
    };
  }
}
